version: "3.8"

services:
  web:
    image: p4179-167:5000/php:7.4-apache  # Image accessible par tout le cluster
    ports:
      - "8080:80"                        # Redirige le port 8080 de l'hôte vers le port 80 du conteneur
    volumes:
      - /var/www/mon-site-web:/var/www/html  # Monte le volume partagé
    deploy:
      replicas: 3                        # Crée 3 instances de ce service
      placement:
        constraints:
          - node.role == worker          # Force l'exécution sur les nœuds worker
