# dynamic_conf.yml
http:
  routers:
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      entryPoints:
        - web
      middlewares:
        - my-middleware
  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://my-service:80"
  middlewares:
    my-middleware:
      headers:
        customRequestHeaders:
          X-Custom-Header: "my-header-value"
