http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  routers:
    traefik:
      rule: "Host(`traefik.mon-vm.com`)"
      service: "api@internal"
      middlewares:
        - redirect-to-https
      entryPoints:
        - websecure
