# traefik.yml (Traefik v3 adapté)
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true  # Mettre à "true" si on veut activer le dashboard sans auth

providers:
  # docker:
  #   swarm: true  # Remplacer swarmMode par swarm pour v3
  #   exposedByDefault: false  # Expose seulement les services avec "traefik.enable=true"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
  swarm:
    network: "publicswarm"  # Utilisation du réseau Swarm

log:
  level: INFO

accessLog: {}

certificatesResolvers:
  myresolver:
    acme:
      email: "ton-email@example.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$$2y$$12$$cA/..."  # Remplace par le hash de ton mot de passe
