version: '3'
services:
  # Service MySQL
  db:
        image: mysql:latest
        container_name: mysql-db
        environment:
          MYSQL_ROOT_PASSWORD: motdepasse
          MYSQL_DATABASE: ma_base_de_donnees
        networks:
          - mon_reseau
        volumes:
          - db_data:/var/lib/mysql

  # Service Web (PHP + Apache)
  web:
        image: php:7.4-apache
        build: .
        container_name: mon-serveur-web
        volumes:
          - toto
        ports:
          - "8080:80"
        networks:
          - mon_reseau
        depends_on:
          - db

# Définir le réseau
networks:
  mon_reseau:
        driver: bridge

# Définir les volumes
volumes:
  db_data:
        external: false
